name: update
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: |
          make deps
      - name: Update cards
        run: |
          make
        env:
          # A separate personal access token is required to read public repos.
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Commit and push changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add docs
          git diff --cached --quiet || git commit -m 'Update cards (from GitHub Actions)'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
